export const productLinePriority = [
  "iPhone",
  "iPhone Pro",
  "iPhone SE",
  "MacBook",
  "MacBook Air",
  "MacBook Pro",
  "iPad",
  "iPad Air",
  "iPad Pro",
  "iPad mini",
  "Apple Pencil",
  "Magic Keyboard for iPad Pro",
  "Apple Watch",
  "Apple Watch Series",
  "Apple Watch SE",
  "Apple Watch Ultra",
  "AirPods",
  "AirPods Pro",
  "AirPods Max",
  "iMac",
  "Mac mini",
  "Mac Pro",
  "Mac Studio",
  "Apple TV 4K",
  "Apple TV HD",
  "HomePod",
  "Accessory",
  "AirTag",
  "Magic Keyboard",
  "Magic Mouse",
  "Magic Trackpad",
  "Studio Display",
  "Vision Pro",
];
